### ISSUE TITLE
/r/worldnews not working

### ISSUE THREAD

**Issue by emil-nasso** [Spacetech/Rebble#2]
I get no content if i add /r/worldnews and a custom subreddit to rebble. All other subs i have tested sees to work.

**Comment by Spacetech** [comment]
Sorry for the late reply. World news doesn't show any threads because there are no self posts / image threads. They are all links to external websites. External website threads don't appear in Rebble.

I could change the behavior and show all threads regardless of the type. The threads that link to external sites could show the comments when you select it.
