### ISSUE TITLE
Very little text being shown in comment threads

### ISSUE THREAD

**Issue by jpalazz2** [Spacetech/Rebble#4]
Very little text is being rendered in comment threads. It appends the "..." after only a line or two of characters. See screenshot:

![pebble_screenshot_2015-11-14_14-20-59](https://cloud.githubusercontent.com/assets/6569083/11165484/b03c9b90-8ade-11e5-840f-2fc13ce0d331.png)

**Comment by dombeef** [comment]
Its an issue of the app trying to make the length of the current "comment" the same length as the previous comment.

I was able to do a work around on an older version of the SDK(for some reason the new one keeps on giving me errors, probably due to the appmessage size increase) by just making the comment length an outrageous number like 5000, but that isnt really a permanent solution.

**Comment by jpalazz2** [comment]
Just committed some code to fix this. Appears to be a weird issue with text_layer_set_text not working exactly as expected.
